[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
Name: ft_package
Version: 0.0.1
Summary: A sample test package
Author: mbouayou
Author-email: mbouayou@1337.student.ma
license = MIT
readme = "README.md"
Metadata-Version: 2.1
Installer: pip
Classifiers:
Entry-points:

[project.urls]
"Homepage" = "https://github.com/mbouayou/ft_package

